# Generated by Django 4.2.13 on 2025-11-12 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('Windows', 'Windows'), ('Web', 'Web'), ('Ios', 'Ios'), ('MacOS', 'MacOS')], max_length=10, verbose_name='پلتفرم')),
                ('maker', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سازنده')),
                ('normal_user_fee', models.CharField(blank=True, choices=[('Free', 'Free'), ('Limited Free', 'Limited Free'), ('Non-free', 'Non-free')], max_length=12, null=True, verbose_name='وضعیت رایگان بودن')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_country', to='setup.country', verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'نرم افزار',
                'verbose_name_plural': 'نرم افزار ها',
            },
        ),
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس وب\u200cسایت')),
                ('org', models.CharField(blank=True, max_length=100, null=True, verbose_name='سازمان')),
                ('as_number', models.CharField(max_length=50, verbose_name='AS')),
                ('asname', models.CharField(max_length=100, verbose_name='AS Name')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تست')),
                ('city', models.CharField(max_length=140, verbose_name='شهر')),
                ('status', models.CharField(choices=[('Filter', 'Filter'), ('Without Filter', 'Without Filter')], max_length=18, verbose_name='وضعیت')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='test.app')),
                ('isp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isps', to='test.isp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تست سرعت',
                'verbose_name_plural': 'تست های سرعت',
            },
        ),
    ]
