# Generated by Django 6.0.1 on 2026-01-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ping_speed',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت پینگ'),
        ),
        migrations.AddField(
            model_name='test',
            name='proxy_port',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='پورت پروکسی'),
        ),
        migrations.AddField(
            model_name='test',
            name='proxy_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رمز پروکسی'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_Latitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عرض جغرافیایی سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_Longitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='طول جغرافیایی سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_city',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='شهر سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_country', to='setup.country', verbose_name='کشور سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_host',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='هاست سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_ip',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='آیپی سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_isp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ارائه دهنده سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='server_region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='منطقه سرور'),
        ),
        migrations.AddField(
            model_name='test',
            name='ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='حجم بسته'),
        ),
    ]
