# Generated by Django 6.0.1 on 2026-01-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_test_ping_speed_test_proxy_port_test_proxy_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ping_speed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='proxy_port',
        ),
        migrations.RemoveField(
            model_name='test',
            name='proxy_secret',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_Latitude',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_Longitude',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_city',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_country',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_host',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_ip',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_isp',
        ),
        migrations.RemoveField(
            model_name='test',
            name='server_region',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ttl',
        ),
    ]
