# Generated by Django 6.0.1 on 2026-01-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_remove_test_ping_speed_remove_test_proxy_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تست'),
        ),
    ]
