# Generated by Django 6.0.1 on 2026-01-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('Windows', 'Windows'), ('Web', 'Web'), ('Ios', 'Ios'), ('MacOS', 'MacOS')], max_length=10, null=True, verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='isp',
            name='as_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AS'),
        ),
        migrations.AlterField(
            model_name='isp',
            name='asname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AS Name'),
        ),
    ]
