# Generated by Django 6.0.1 on 2026-01-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_alter_app_platform_alter_isp_as_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isp',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس وب\u200cسایت'),
        ),
    ]
